#!/usr/bin/env python3
import requests
from pyquery import PyQuery as pq
import argparse

def word_lookup(word):
    response = requests.get('http://www.wordreference.com/definicion/{}'.format(word))

    dom = pq(response.text)

    sug = dom('#spellSug')
    if sug:
        print('No encontré {}, pero podrías buscar:'.format(word))
        print()

        sug_res = requests.get('http://spell.wordreference.com/spell/spellAC.php?w={}&dict=eses&reverse='.format(word))
        sugestions = map(
            lambda x: x.split('\t')[0],
            filter(
                lambda x:x,
                sug_res.text[3:].split('\n')
            )
        )

        for sugestion in sugestions:
            print('\t' + sugestion)

        exit()

    trans = dom('#article').find('.trans')

    for trindex, t in enumerate(trans):
        print('\n{} ({})'.format(t.find('h3').text, trindex+1), end='\n\n')

        for index, element in enumerate(t.find('ol')):
            print('\t{}. {}'.format(index+1, element.text_content().strip()))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Search word definitions in wordreference')

    parser.add_argument('word', type=str, help='the word to look the definition for')

    args = parser.parse_args()

    word_lookup(args.word)
